Use console.dir instead of console.log for better object viewing
tablelandnetwork/js-tableland-cli pull request #202
Opened 2023-02-14 19:38 UTC by awmuncy

2023-02-14 19:56 UTC, carsonfarmer requested changes

2023-02-14 19:56 UTC, carsonfarmer commented on src/commands/namespace.ts
> +      console.log(response, { depth: null });
Should this be `console.dir`?

2023-02-14 20:03 UTC, awmuncy commented on src/commands/namespace.ts
> +      console.log(response, { depth: null });
Yes, fixed.

2023-02-14 20:10 UTC, carsonfarmer approved these changes
🤌

2023-02-14 20:21 UTC, merged

2023-02-15 15:39 UTC, awmuncy commented
Note: Solved issue #201